name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Transform to GVLAUNCHER
      run: |
        # 1. Изменение ID приложения на твой пакет
        find . -type f -name "build.gradle" -exec sed -i 's/applicationId ".*"/applicationId "NET.GVLAUNCHER.VYACHESLAV20K"/g' {} +
        find . -type f -name "build.gradle.kts" -exec sed -i 's/applicationId = ".*"/applicationId = "NET.GVLAUNCHER.VYACHESLAV20K"/g' {} +

        # 2. Поиск и замена названия приложения на GVLAUNCHER
        STRINGS_FILE=$(find . -type f -path "*/src/main/res/values/strings.xml" | head -n 1)
        if [ -f "$STRINGS_FILE" ]; then
            sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">GVLAUNCHER<\/string>/g' "$STRINGS_FILE"
        fi

        # 3. Поиск и замена цветов темы на синий
        COLORS_FILE=$(find . -type f -path "*/src/main/res/values/colors.xml" | head -n 1)
        if [ -f "$COLORS_FILE" ]; then
            sed -i 's/<color name="colorPrimary">.*<\/color>/<color name="colorPrimary">#0D47A1<\/color>/g' "$COLORS_FILE"
            sed -i 's/<color name="colorPrimaryDark">.*<\/color>/<color name="colorPrimaryDark">#0A3578<\/color>/g' "$COLORS_FILE"
            sed -i 's/<color name="colorAccent">.*<\/color>/<color name="colorAccent">#2979FF<\/color>/g' "$COLORS_FILE"
        fi

        # 4. Замена ссылок на твои Telegram и Discord
        find . -type f \( -name "*.java" -o -name "*.xml" -o -name "*.json" -o -name "*.kt" \) -exec sed -i 's|https://t.me/[A-Za-z0-9_]*|https://t.me/GAMEVANILAPrivateServer|g' {} +
        find . -type f \( -name "*.java" -o -name "*.xml" -o -name "*.json" -o -name "*.kt" \) -exec sed -i 's|https://discord.gg/[A-Za-z0-9_]*|https://discord.gg/6f4SqmhWa|g' {} +

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Build Android APK
      run: ./gradlew assembleDebug --no-daemon -x test

    - name: Upload GVLAUNCHER Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: GVLauncher-Build
        path: |
          **/*.apk
          **/build/outputs/apk/**/*.apk
